export const ALIASES = {
  meters: 'meter',
  inches: 'inch',
  feet: 'foot',
  yards: 'yard',
  miles: 'mile',
  links: 'link',
  rods: 'rod',
  chains: 'chain',
  angstroms: 'angstrom',

  lt: 'l',
  litres: 'litre',
  liter: 'litre',
  liters: 'litre',
  teaspoons: 'teaspoon',
  tablespoons: 'tablespoon',
  minims: 'minim',
  fluiddrams: 'fluiddram',
  fluidounces: 'fluidounce',
  gills: 'gill',
  cups: 'cup',
  pints: 'pint',
  quarts: 'quart',
  gallons: 'gallon',
  beerbarrels: 'beerbarrel',
  oilbarrels: 'oilbarrel',
  hogsheads: 'hogshead',
  gtts: 'gtt',

  grams: 'gram',
  tons: 'ton',
  tonnes: 'tonne',
  grains: 'grain',
  drams: 'dram',
  ounces: 'ounce',
  poundmasses: 'poundmass',
  hundredweights: 'hundredweight',
  sticks: 'stick',
  lb: 'lbm',
  lbs: 'lbm',

  kips: 'kip',
  kgf: 'kilogramforce',

  acres: 'acre',
  hectares: 'hectare',
  sqfeet: 'sqft',
  sqyard: 'sqyd',
  sqmile: 'sqmi',
  sqmiles: 'sqmi',

  mmhg: 'mmHg',
  mmh2o: 'mmH2O',
  cmh2o: 'cmH2O',

  seconds: 'second',
  secs: 'second',
  minutes: 'minute',
  mins: 'minute',
  hours: 'hour',
  hr: 'hour',
  hrs: 'hour',
  days: 'day',
  weeks: 'week',
  months: 'month',
  years: 'year',
  decades: 'decade',
  centuries: 'century',
  millennia: 'millennium',

  hertz: 'hertz',

  radians: 'radian',
  degrees: 'degree',
  gradians: 'gradian',
  cycles: 'cycle',
  arcsecond: 'arcsec',
  arcseconds: 'arcsec',
  arcminute: 'arcmin',
  arcminutes: 'arcmin',

  BTUs: 'BTU',
  watts: 'watt',
  joules: 'joule',

  amperes: 'ampere',
  coulombs: 'coulomb',
  volts: 'volt',
  ohms: 'ohm',
  farads: 'farad',
  webers: 'weber',
  teslas: 'tesla',
  electronvolts: 'electronvolt',
  moles: 'mole',

  bit: 'bits',
  byte: 'bytes'
}
